repos:
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: migrations/
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        exclude: migrations/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args: [ '--autofix', '--no-sort-keys' ]
      - id: check-byte-order-marker
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        additional_dependencies: [ toml ]
        exclude: migrations/
